apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: gcr.io/lbg-mea-14/ak-trio-task-db:latest
    ports:
    - containerPort: 3306
    env:
    - name: PASSWORD
      value: Badger1
    - name: MYSQL_ROOT_PASSWORD
      value: Badger1
    - name: MYSQL_DATABASE
      value: flask-db
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports: 
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP


